import csv
import json

data = { 
    "Shipment ID": "",
    "Carrier Name": "",
    "Vessel Name": "",
    "Gross Weight": "",
    "Volume": "",
    "Ocean Bill of Lading(s)": "",
    "House Bill Number": "",
    "Load Port": "",
    "Discharge Port": "",
    "Shipper Name": "",
    "Consignee Name": "",
    "Ultimate Consignee Name": "",
    "Delivered Location": "",
    "In Gate Location": "",
    "Shipment Ready Location": "",
    "Storage Last Free Day Location": "",
    "Rail Ramp Location": "",
    "Rail Depart Location": "",
    "Rail Arrive Location": "",
    "Pick Up Location": "",
    "Out Gate Location": "",
    "Origin Location": "",
    "Loaded on Rail Location": "",
    "Customs Hold Location": "",
    "Container Loaded Location": "",
    "Equipment Type": "",
    "Equipment ID": "",
    "Seal Number": "",
    "Actual In Gate": "",
    "Estimated Depart": "",
    "Actual Depart": "",
    "Estimated Arrive": "",
    "Actual Arrive": "",
    "Actual Out Gate": "",
    "Estimated Delivered": "",
    "Actual Delivered": "",
    "Transit Depart to Arrive (C)": "",
    "Total TEU": "",
    "Insert Date": " ",
    "Actual Available for Pickup": " ",
    "Actual Loaded on Rail": "",
    "Container Loaded Location": "",
    "En Route Location Order ID": "",
    "Item #": "",
    "Total Qty Shipped": "",
     }

all_data = []

with open('latest_demo_data.csv') as csvfile:
    readCSV = csv.reader(csvfile, delimiter=',')
    for row in readCSV:
        data = { 
                "Shipment ID": row[0],
                "Carrier Name": row[1],
                "Vessel Name": row[2],
                "Gross Weight": row[3],
                "Volume": row[4],
                "Ocean Bill of Lading(s)": row[5],
                "House Bill Number": row[6],
                "Load Port": row[7],
                "Discharge Port": row[8],
                "Shipper Name": row[9],
                "Consignee Name": row[10],
                "Ultimate Consignee Name": row[11],
                "Delivered Location": row[12],
                "In Gate Location": row[13],
                "Shipment Ready Location": row[14],
                "Storage Last Free Day Location": row[15],
                "Rail Ramp Location": row[16],
                "Rail Depart Location": row[17],
                "Rail Arrive Location": row[18],
                "Pick Up Location": row[19],
                "Out Gate Location": row[20],
                "Origin Location": row[21],
                "Loaded on Rail Location": row[22],
                "Customs Hold Location": row[23],
                "Container Loaded Location": row[24],
                "Equipment Type": row[25],
                "Equipment ID": row[26],
                "Seal Number": row[27],
                "Actual In Gate": row[28],
                "Estimated Depart": row[29],
                "Actual Depart": row[30],
                "Estimated Arrive": row[31],
                "Actual Arrive": row[32],
                "Actual Out Gate": row[33],
                "Estimated Delivered": row[34],
                "Actual Delivered": row[35],
                "Transit Depart to Arrive (C)": row[36],
                "Total TEU": row[37],
                "Insert Date": row[38],
                "Actual Available for Pickup": row[39],
                "Actual Loaded on Rail": row[40],
                "Container Loaded Location": row[41],
                "En Route Location Order ID": row[42],
                "Item #": row[43],
                "Total Qty Shipped": row[44],
     }
        all_data.append(data)

with open('data_new.txt', 'w') as outfile:
    json.dump(all_data, outfile)
